content/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', main_page, name="main"),
    path('events', events, name="events"),
    path('camps', CampsView.as_view(), name='camps'),
    path('tournament', TournamentsView.as_view(), name="tournaments"),
    path('tournament/<int:pk>', TournamentDetailView.as_view(), name="dtour"),
    path('tournament/create-application', create_team, name="application"),
    path('contacts', contacts, name="contacts"),
    path('news', NewsView.as_view(), name="news"),
    path('news/<int:pk>', NewsDetailView.as_view(), name="dnews"),
    path('camps/<int:pk>', CampsDetailView.as_view(), name="dcamp"),
    path('footballfield', footballfield, name="field"),
    path('training', trainingpage, name="training"),
    path('club', clubs, name="club"),
    path('agency', agency, name="agency")

]

footballplanet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('content.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='content/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='content/logout.html'), name='logout'),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

content/models.py
from django.db import models
from datetime import *

# Create your models here.
class Tournaments(models.Model):
    name = models.CharField(max_length=255)
    logo = models.ImageField(upload_to='content/static/content/images/tournaments', null=True)
    start_date = models.DateField()
    end_date = models.DateField()
    category = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    description = models.CharField(max_length=255, default=' ')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Tournaments"
        verbose_name_plural = "Tournaments"

class Team(models.Model):
    name = models.CharField(max_length=255)
    logo = models.ImageField(upload_to="content/static/content/images/teams", null=True)
    tournament = models.ForeignKey(Tournaments, on_delete=models.CASCADE)
    country = models.CharField(max_length=255)
    countOfPlayers = models.IntegerField()
    coach = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    pnumber = models.CharField(max_length=12)
    info = models.CharField(max_length=1000)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Team"
        verbose_name_plural = "Team"

class SquadList(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    sname = models.CharField(max_length=255)
    pos = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "SquadList"
        verbose_name_plural = "SquadList"


class FootballCamp(models.Model):
    name = models.CharField(max_length=255)
    logo = models.ImageField(upload_to='content/static/content/images/camps', null=True)
    description = models.TextField()
    youtube_link = models.URLField(blank=True, null=True)
    mini_player_code = models.TextField(blank=True, null=True)
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    # Фотогалерея
    photo_gallery = models.ManyToManyField('Photo', related_name='camps', blank=True)

    def __str__(self):
        return self.name

class Photo(models.Model):
    image = models.ImageField(upload_to='content/static/content/images')
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"Photo {self.id}"

class Trainer(models.Model):
    name = models.CharField(max_length=255)
    pcoach = models.ImageField(upload_to='content/static/content/images/coaches', null=True )
    description = models.TextField()

    def __str__(self):
        return self.name

class Training(models.Model):
    camp = models.ForeignKey(FootballCamp, on_delete=models.CASCADE, related_name='trainings')
    photo = models.ForeignKey(Trainer, on_delete=models.CASCADE, related_name='training_photos', null=True  )
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE, related_name='related_trainings')
    training_description = models.TextField()

    def __str__(self):
        return f"{self.trainer} - {self.camp.name}"



class Match(models.Model):
    tournament = models.ForeignKey(Tournaments, on_delete=models.CASCADE)
    date_time = models.DateTimeField()
    team_home = models.ForeignKey(Team, related_name='home_matches', on_delete=models.CASCADE)
    team_away = models.ForeignKey(Team, related_name='away_matches', on_delete=models.CASCADE)
    result_home = models.IntegerField(null=True, blank=True)
    result_away = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.team_home} vs. {self.team_away} - {self.date_time}"

class Standing(models.Model):
    tournament = models.ForeignKey(Tournaments, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    group = models.CharField(max_length=2)
    points = models.IntegerField(default=0)
    goals_for = models.IntegerField(default=0)
    goals_against = models.IntegerField(default=0)
    goal_difference = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.team} - Points: {self.points}"


class Contact(models.Model):
    name = models.CharField(max_length=255, null=True)
    email = models.CharField(max_length=255, null=True)
    topic = models.CharField(max_length=255, null=True)
    phone_number = models.CharField(max_length=20, null=True)
    message = models.TextField()

    def __str__(self):
        return self.name

class NewsFootball(models.Model):
    name = models.CharField(max_length=255)
    autor = models.CharField(max_length=255)
    photo = models.ImageField(upload_to="content/static/content/images/news")
    time_of_publication = models.DateTimeField(null=True)
    text = models.TextField()

    def __str__(self):
        return self.name

content/forms.py
from django.contrib.auth.models import User
from .models import *
from django.forms import ModelForm, TextInput, Textarea, DateTimeInput, EmailInput, PasswordInput, CharField, EmailField
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.db import models
from django import forms
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget

class createApplication(ModelForm):
    class Meta:
        model = Team
        # 9 fields
        fields = ['name', 'logo', 'tournament', 'country', 'countOfPlayers', 'coach', 'email', 'pnumber', 'info']

        labels = {
            'name': '',
            'logo': '',
            'tournament': '',
            'country': '',
            'countOfPlayers': '',
            'coach': '',
            'email': '',
            'pnumber': '',
            'info': ''
        }

        widgets = {
            'name': TextInput(attrs={'class': 'form-application', 'placeholder': 'Название(в названии укажите категорию)'}),
            'country': TextInput(attrs={'class': 'form-application', 'placeholder': 'Страна'}),
            'countOfPlayers': TextInput(attrs={'class': 'form-application', 'placeholder': 'Турнир'}),
            'coach': TextInput( attrs={'class': 'form-application', 'placeholder': 'Тренер команды'}),
            'email': EmailInput(attrs={'class': 'form-application', 'placeholder': 'E-mail'}),
            'pnumber': PhoneNumberPrefixWidget(attrs={'class': 'form-application', 'placeholder': 'Номер телефона'}),
            'info': Textarea(attrs={'class': 'form-application', 'placeholder': 'Дополнительная информация'})

        }

class sendContact(ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'phone_number', 'topic', 'message']

        labels = {
            'name': '',
            'email': '',
            'topic': '',
            'message': '',
            'phone_number': ''
        }

        widgets = {
            'name': TextInput(
                attrs={'class': 'contact-form-fp', 'id': 'contact-fp-form-name', 'placeholder': 'Ваше имя'}),
            'email': EmailInput(
                attrs={'class': 'contact-form-fp', 'id': 'contact-fp-form-email', 'placeholder': 'Email'}),
            'topic': TextInput(
                attrs={'class': 'contact-form-fp', 'id': 'contact-fp-form-topic', 'placeholder': 'Тема'}),
            'phone_number': TextInput(
                attrs={'class': 'contact-form-fp', 'id': 'contact-fp-form-phone_number', 'placeholder': 'Номер телефона'}),
            'message': Textarea(
                attrs={'class': 'contact-form-fp', 'id': 'contact-fp-form-message', 'placeholder': 'Сообщение'})

        }

content/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import *
from .forms import *
from itertools import chain

# Create your views here.

def main_page(request):
    current_datetime = datetime.now()
    upcoming_tournaments = Tournaments.objects.filter(start_date__gte=current_datetime).order_by('start_date')[:3]
    upcoming_football_camps = FootballCamp.objects.filter(start_date__gte=current_datetime).order_by('start_date')[:3]
    events = sorted(
        chain(upcoming_tournaments, upcoming_football_camps),
        key=lambda event: event.start_date
    )[:3]
    news = NewsFootball.objects.all()

    context = {
        'events': events,
        'news': news,
    }
    return render(request, 'content/main.html', context)

def trainingpage(request):
    return render(request, 'content/training.html')

def clubs(request):
    return render(request, 'content/club.html')

def footballfield(request):
    return render(request, 'content/footballfield.html')

def agency(request):
    return render(request, 'content/agency.html')

def events(request):
    latest_tournaments = Tournaments.objects.order_by('-start_date')[:3]
    latest_camps = FootballCamp.objects.order_by('-start_date')[:3]

    return render(request, 'content/events.html',
                  {'latest_tournaments': latest_tournaments, 'latest_camps': latest_camps})


def contacts(request):
    if request.method == 'POST':
        form = sendContact(request.POST)
        if form.is_valid():
            form.save()
            return redirect('contacts')
    else:
        form = sendContact()
    return render(request, 'content/contact.html', {'form': form})

class CampsView(ListView):
    model = FootballCamp
    template_name = "content/camps.html"
    context_object_name = "camps"

class TournamentsView(ListView):
    model = Tournaments
    template_name = "content/tournaments.html"
    context_object_name = "tournaments"

class NewsView(ListView):
    model = NewsFootball
    template_name = "content/news.html"
    context_object_name = "news"

class NewsDetailView(DetailView):
    model = NewsFootball
    template_name = "content/newsDetail.html"
    context_object_name = "news"

class TournamentDetailView(DetailView):
    model = Tournaments
    template_name = "content/detailTournament.html"
    context_object_name = "tournaments"

class CampsDetailView(DetailView):
    model = FootballCamp
    template_name = "content/detailCamps.html"
    context_object_name = "camp"

def create_team(request):
    if request.method == 'POST':
        form = createApplication(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('main')  # Замените 'success_page' на URL страницы, куда перенаправить после успешного сохранения
    else:
        form = createApplication()

    return render(request, 'content/application.html', {'form': form})

content/templates/content/agency.html
{% extends 'content/index.html' %}
{% load static %}

{% block title %}Агентсво FP{% endblock %}

{% block main %}


<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'content/images/fp_agency_1920px.png' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>   
      <div class="container">
        <div class="row no-gutters slider-text align-items-end">
          <div class="col-md-9 ftco-animate pb-5">
          	<p class="breadcrumbs mb-2"><span class="mr-2"><a href="{% url 'main' %}">Главная <i class="ion-ios-arrow-forward"></i></a></span> <span>Агентсво FP <i class="ion-ios-arrow-forward"></i></span></p>
            <h1 class="mb-0 bread">Агентсво FP</h1>
          </div>
        </div>
      </div>
</section>

<section class="agency-fp">

	<h2>Агентсво FP</h2>	
	<div class="box-agency">
		<div class="image-box-agency">
			<img src="{% static 'content/images/cropped-logo-color.png' %}">			
		</div>
		<div class="text-box-agency">
			<p>Компания FOOTBALLPLANET основана в 2017 году. Головной офис компании находится в Эстонии. Партнеры FOOTBALLPLANET есть в Испании и России. Наши международные связи не ограничиваются лишь странами двумя странами, мы активно работаем и с другими странами Европы и Азии .</p>
			<p>Мы предлагаем интегрированные услуги по заключению контрактов, переходу футболистов, улучшению условий контрактов.</p>
			<p>Перечень услуг, предоставляемых компанией, включает в себя консалтинг клубов, а так же менеджмент футболистов. Поиск юных талантов.</p>
		</div>
	</div>
	<h2>Наши игроки</h2>
	<p></p>
	<p></p>

</section>

{% endblock %}

content/templates/content/camps.html
{% extends 'content/index.html' %}
{% load static %}

{% block title %}Лагеря{% endblock %}
{% block main %}
<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'content/images/camps-header.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>   
      <div class="container">
        <div class="row no-gutters slider-text align-items-end">
          <div class="col-md-9 ftco-animate pb-5">
          	<p class="breadcrumbs mb-2"><span class="mr-2"><a href="{% url 'main' %}">Главная <i class="ion-ios-arrow-forward"></i></a></span> <span><a href="{% url 'events' %}">События <i class="ion-ios-arrow-forward"></i></a></span> <span>Лагеря <i class="ion-ios-arrow-forward"></i></span></p>
            <h1 class="mb-0 bread">Лагеря</h1>
          </div>
        </div>
      </div>
</section>

<h2 class="events-h2">Лагеря</h2>

    <div class="tournaments">
        {% for camp in camps %}
            <div class="tournament">
                <a href="#">
                    <img src="{% static camp.logo|cut:'content/static/' %}" alt="{{ camp.name }}">
                </a>
                <div class="tournament-info">
                    <div class="tournament-dates">
                        <div class="tournament-date">{{ camp.start_date }}</div>
                        <div class="tournament-date">{{ camp.end_date }}</div>
                    </div>
                    <h2 class="tournament-title"><a href="{% url 'dcamp' camp.id %}">{{ camp.name }}</a></h2>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

content/templates/content/contact.html
{% extends 'content/index.html' %}
{% load static %}

{% block title %}Контакты{% endblock %}
{% block main %}

    <section class="hero-wrap hero-wrap-2" style="background-image: url('{% static 'content/images/contact-header.jpg' %}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end">
          <div class="col-md-9 ftco-animate pb-5">
          	<p class="breadcrumbs mb-2"><span class="mr-2"><a href="{% url 'main' %}">Главная <i class="ion-ios-arrow-forward"></i></a></span> <span>Контакты <i class="ion-ios-arrow-forward"></i></span></p>
            <h1 class="mb-0 bread">Наши контакты</h1>
          </div>
        </div>
      </div>
    </section>
   	<section class="info-contact-fp">
   		<div class="box-contact-fp">
   			<div class="contact-text-fp">
		   		<div class="adress-fp">
		   			<h3>Адрес:</h3>
		   			<p>Kalda 9a, Tallinn, Estonia</p>
		   		</div>
		   		<div class="shedule-fp">
		   			<h3>Рассписание</h3>
		   			<p>Пн-Вс с 9:00 - 22:00</p>
		   		</div>
		   		<div class="phone-number-fp">
		   			<p>Nikita Martynov +372 5622 5993 (RUS, EST, ENG, ESP)</p>
		   		</div>
		   		<div class="social-media-fp">
		   			<h3>Мы в соцсетях</h3>
		   			<ul>
		   				<li style="float: left; margin-right: 10px; "><a href="https://www.facebook.com/profile.php?id=100090402353092"><img src="{% static 'content/images/facebook.svg' %}"></a></li>
		   				<li><a href="https://www.instagram.com/footballplanet.top/"><img src="{% static 'content/images/instagram.svg' %}"></a></li>
		   			</ul>
		   		</div>
		   	</div>
	   		<div class="google-maps-fp-contact">
	   			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2031.9452812406175!2d24.634708776446036!3d59.38394020664899!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x469295a29fe512bf%3A0xd69a05615ec2fd0c!2zS2FsZGEgOUEsIDExNjI1IFRhbGxpbm4sINCt0YHRgtC-0L3QuNGP!5e0!3m2!1sru!2ses!4v1701891017348!5m2!1sru!2ses" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
	   		</div>
	   	</div>
	   	
    

				<div class="contact-wrap w-100 p-md-5 p-4 contact-area-fp">
					<h3 class="mb-4">Свяжитесь с нами</h3>
					<div id="form-message-warning" class="mb-4"></div> 
      				<div id="form-message-success" class="mb-4">
		            	<form method="POST" id="contact-form-fp">
		            		{% csrf_token %}
		            		{{ form.as_p }}
		            		<button id="form-button-fp" type="submit">Отправить</button>
		            	</form>
      				</div>
					
				</div>
			
		</section>			


    <style type="text/css">
    	.social-media-fp ul li {
    		list-style-type: none;
    	}
    	.social-media-fp ul li img {
    		height: 50px;
    		width: 50px;
    	}
    	@media only screen and (max-width: 1000px) {
	        .contact-text-fp {
	            order: 1; 
	        }
	        .google-maps-fp-contact {
	            order: 2; 
	            overflow: hidden;
	            position: relative;
	            padding-bottom: 75%; 
	            height: 0;
	            margin-bottom: 20px;
	            
	        }
	        .google-maps-fp-contact iframe {
	        	position: absolute;
	            top: 0;
	            left: 0;
	            width: 100%;
	            height: 100%;

	        }
	        
	        .contact-wrap {
	        	margin-top: 50px;
	            order: 3; 
	        }
	    }

	    
	    @media only screen and (min-width: 1000px) {
	        .contact-text-fp {
	            width: 30%; 
	            float: left; 
	        }
	        .google-maps-fp-contact {
	            width: 50%; 
	            float: right; 
	            margin-right: 15%;
	            height: 60%;
	        }
	        .contact-wrap {
	            clear: both; 
	            margin-top: 50px;
	        }
	        .box-contact-fp {
	        	height: 450px;
	        }
	    }
    </style>

{% endblock %}

content/templates/content/detailCamps.html
{% extends 'content/index.html' %}
{% load static %}

{% block title %}
    {{ camp.name }}
{% endblock %}

{% block main %}

<section class="hero-wrap hero-wrap-2" style="background-image: url({% static camp.logo|cut:'content/static/' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>   
      <div class="container">
        <div class="row no-gutters slider-text align-items-end">
          <div class="col-md-9 ftco-animate pb-5">
          	
            <h1 class="mb-0 bread">{{ camp.name }}</h1>
            <p class="camp-description-fp">{{ camp.description }}</p>
            <p class="breadcrumbs mb-2"><span class="mr-2"><a href="{% url 'main' %}">Главная <i class="ion-ios-arrow-forward"></i></a></span> <span><a href="{% url 'events' %}">События <i class="ion-ios-arrow-forward"></i></a></span> <span>Лагеря <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
</section>

<section class="camps-section-fp">
	<h2 class="events-h2">{{ camp.name }}</h2>
	<h2 class="camps-h2">Видео</h2>
	<div class="yt-window-fp">{{ camp.mini_player_code|safe }}</div>
	<h2 class="camps-h2">Фотогалерея</h2>
	<div class="tournaments">
		{% for photo in camp.photo_gallery.all %}
		<div class="tournament">
            <img class="photo-galety-fp" src="{% static photo.image|cut:'content/static/' %}" alt="{{ photo.description }}">
            <p>{{ photo.description }}</p>
		</div>
		{% endfor %}
	</div>
	<h2 class="camps-h2">Тренера</h2>
    <div class="tournaments">
        {% for training in camp.trainings.all %}
            <div class="tournament">
            	<img src="{% static training.trainer.pcoach|cut:'content/static/' %}" alt="{{ training.trainer }}">
                <p>{{ training.trainer }}</p>
                <p>{{ training.training_description }}</p>
                <!-- Add more fields as needed -->
            </div>
        {% endfor %}
    </div>


</section>

{% endblock %}

content/templates/content/detailTournament.html
{% extends 'content/index.html' %}
{% load static %}

{% block title %}
    {{ tournament.name }}
{% endblock %}

{% block main %}
    <h1>{{ tournament.name }}</h1>
    <p><strong>Start Date:</strong> {{ tournaments.start_date }}</p>
    <p><strong>End Date:</strong> {{ tournaments.end_date }}</p>
    <p><strong>Description:</strong> {{ tournaments.description }}</p>
    <p><strong>Location:</strong> {{ tournaments.location }}</p>

    <h2>Teams:</h2>
    <ul>
        {% for team in tournaments.team_set.all %}
            <li>{{ team.name }}</li>
        {% endfor %}
    </ul>

    <h2>Matches:</h2>
    <ul>
        {% for match in tournaments.match_set.all %}
            <li>{{ match.team_home.name }} vs. {{ match.team_away.name }} - {{ match.date_time }}</li>
        {% endfor %}
    </ul>

    <h2>Standings:</h2>
    <table>
        <thead>
            <tr>
                <th>Team</th>
                <th>Points</th>
                <th>Goals For</th>
                <th>Goals Against</th>
                <th>Goal Difference</th>
            </tr>
        </thead>
        <tbody>
            {% for standing in tournaments.standing_set.all %}
                <tr>
                    <td>{{ standing.team.name }}</td>
                    <td>{{ standing.points }}</td>
                    <td>{{ standing.goals_for }}</td>
                    <td>{{ standing.goals_against }}</td>
                    <td>{{ standing.goal_difference }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

content/templates/content/footballfield.html
{% extends 'content/index.html' %}
{% load static %}

{% block title %}Аренда поля{% endblock %}

{% block main %}

<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'content/images/rent-header.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>   
      <div class="container">
        <div class="row no-gutters slider-text align-items-end">
          <div class="col-md-9 ftco-animate pb-5">
          	<p class="breadcrumbs mb-2"><span class="mr-2"><a href="{% url 'main' %}">Главная <i class="ion-ios-arrow-forward"></i></a></span> <span>Аренда поля <i class="ion-ios-arrow-forward"></i></span></p>
            <h1 class="mb-0 bread">Аренда поля</h1>
          </div>
        </div>
      </div>
</section>

<section class="field-fp info-contact-fp">
	<div class="img-rent">
		<img src="{% static 'content/images/football-field.jpg' %}">
	</div>
	<div class="box-contact-fp">
   		<div class="contact-text-fp">
			<div class="adress-fp">
				<h3>Адрес:</h3>
				<p>Kalda 9a, Tallinn, Estonia</p>
			</div>
			<div class="phone-number-fp">
				<p>Nikita Martynov +372 5622 5993 (RUS, EST)</p>
			</div>
			<div class="google-maps-fp-contact">
			   	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2031.9452812406175!2d24.634708776446036!3d59.38394020664899!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x469295a29fe512bf%3A0xd69a05615ec2fd0c!2zS2FsZGEgOUEsIDExNjI1IFRhbGxpbm4sINCt0YHRgtC-0L3QuNGP!5e0!3m2!1sru!2ses!4v1701891017348!5m2!1sru!2ses" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
			</div>
		</div>
	</div>
	<div class="contact-wrap w-100 p-md-5 p-4 contact-area-fp">
					<h3 class="mb-4">Свяжитесь с нами</h3>
					<div id="form-message-warning" class="mb-4"></div> 
      				<div id="form-message-success" class="mb-4">
		            	<form method="POST" id="contact-form-fp">
		            		{% csrf_token %}
		            		{{ form.as_p }}
		            		<button id="form-button-fp" type="submit">Отправить</button>
		            	</form>
      				</div>
					
				</div>
</section>

<style type="text/css">
		.contact-text-fp {
			color: black;
		}
		.contact-text-fp h3 {
			font-weight: 550;
		}
		.img-rent  img{
			width: 80%;
			height: auto;
			margin: 5%;
			display: block;
		}

    	.social-media-fp ul li {
    		list-style-type: none;
    	}
    	.social-media-fp ul li img {
    		height: 50px;
    		width: 50px;
    	}
    	@media only screen and (max-width: 1000px) {
	        .contact-text-fp {
	            order: 1; 
	        }
	        .google-maps-fp-contact {
	            order: 2; 
	            overflow: hidden;
	            position: relative;
	            padding-bottom: 75%; 
	            height: 0;
	            margin-bottom: 20px;
	            
	        }
	        .google-maps-fp-contact iframe {
	        	position: absolute;
	            top: 0;
	            left: 0;
	            width: 100%;
	            height: 100%;

	        }
	        
	        .contact-wrap {
	        	margin-top: 50px;
	            order: 3; 
	        }
	    }

	    
	    @media only screen and (min-width: 1000px) {
	        .contact-text-fp {
	            width: 30%; 
	            float: left; 
	        }
	        .google-maps-fp-contact {
	            width: 50%; 
	            float: right; 
	            margin-right: 15%;
	            height: 60%;
	        }
	        .contact-wrap {
	            clear: both; 
	            margin-top: 50px;
	        }
	        .box-contact-fp {
	        	height: 450px;
	        }
	    }
    </style>

{% endblock %}

content/templates/content/newsDetail.html
{% extends 'content/index.html' %}
{% load static %}

{% block title %}
    {{ news.name }}
{% endblock %}

{% block main %}
<section class="hero-wrap hero-wrap-2" style="background-image: url({% static news.photo|cut:'content/static/' %});" data-stellar-background-ratio="0.5">
  	<div class="overlay"></div>   
  	<div class="container">
    	<div class="row no-gutters slider-text align-items-end">
      		<div class="col-md-9 ftco-animate pb-5">
          		<p class="breadcrumbs mb-2"><span class="mr-2"><a href="{% url 'main' %}">Главная <i class="ion-ios-arrow-forward"></i></a></span> <span><a href="{% url 'news' %}">Новости <i class="ion-ios-arrow-forward"></i></a></span> <span>{{ news.name }} <i class="ion-ios-arrow-forward"></i></span></p>
            	<h1 class="mb-0 bread">{{ news.name }}</h1>
      		</div>
    	</div>
  	</div>
</section>
<section class="detail-news-fp">
	<div class="news-area-fp">
		<h2 class="events-h2">{{ news.name }}</h2>
		<img src="{% static news.photo|cut:'content/static/' %}" alt="{{ el.name }}">
		<p>{{ news.autor }}</p>
		<p>{{ news.time_of_publication }}</p>
		<div class="news-text-fp">{{ news.text|linebreaksbr }}</div>

		
	</div>
</section>

{% endblock %}